apiVersion: batch/v1
kind: Job
metadata:
  name: {{appName}}-job
  labels:
    name: {{appName}}-job
    env: {{env}}
spec:
  template:
      metadata:
        labels:
          name: {{appName}}-job
          env: {{env}}
    spec:
      containers:
      - name: test
        image: frolvlad/alpine-oraclejdk8:slim
        command: "{{command}}"
        env:
        - name: PAAS_TYPE
          value: "k8s"
        - name: APPLICATION_URL
          value: "http://{{appName}}"
        - name: STUBRUNNER_URL
          value: "http://{{stubrunnerName}}"
        volumeMounts:
          - mountPath: "/var/jenkins_home/"
            name: "user-smoke-volume-claim"
          - mountPath: "/root/"
            name: "root-smoke-volume-claim"
      volumes:
        - name: "user-smoke-volume-claim"
          persistentVolumeClaim:
            claimName: "user-smoke-volume-claim"
        - name: "root-smoke-volume-claim"
          persistentVolumeClaim:
            claimName: "root-smoke-volume-claim"
      restartPolicy: Never