apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{appName}}
spec:
  replicas: 1
  template:
      metadata:
        labels:
          name: {{appName}}
          env: {{env}}
      spec:
        containers:
        - name: {{appName}}
          image: {{stubrunnerImg}}
          ports:
          - containerPort: 8080
          env:
          - name: PORT
            value: "8080"
          - name: SPRING_RABBITMQ_ADDRESSES
            value: "{{rabbitAppName}}"
          - name: eureka_client_serviceUrl_defaultZone
            value: "http://{{eurekaAppName}}:8761/eureka/"
          - name: STUBRUNNER_IDS
            value: "{{stubrunnerIds}}"
          - name: STUBRUNNER_REPOSITORY_ROOT
            value: "{{repoWithJars}}"
#          livenessProbe:
#            httpGet:
#              path: /health
#              port: 8080
#            initialDelaySeconds: 180
#            periodSeconds: 3